### ISSUE TITLE
`--generate-dir` works confusingly

### ISSUE THREAD

**Issue by stefanw** [simonw/datasette-publish-fly#18]
I tried out `--generate-dir` and ran into two problems with the code that's responsible:

https://github.com/simonw/datasette-publish-fly/blob/564a216508466b9cb1d0b30fe90199fc8546df46/datasette_publish_fly/__init__.py#L313-L322

- It can only copy files, not directories (e.g. the plugin directory!)
- If you give a relative path, the directory is generated not in the current working directory, but in the temporary directory which is cleaned up afterwards!

As a workaround I had to give an absolute path, but that was after some confusion and digging into the code.

**Comment by simonw** [comment]
Yeah that's a good call: `generate_dir` being resolved relative to that temporary directory is most definitely a bug!

**Comment by simonw** [comment]
Replicated that other bug locally:

    datasette publish fly github.db -a wat --generate-dir foop --plugins plugins

Which does this:

```
  File "/Users/simon/.pyenv/versions/3.10.0/lib/python3.10/shutil.py", line 417, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/Users/simon/.pyenv/versions/3.10.0/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
IsADirectoryError: [Errno 21] Is a directory: 'plugins'
```
Code at fault is:

https://github.com/simonw/datasette-publish-fly/blob/68b809fe6abb6dd9aa076106ccfe824f0ccea1da/datasette_publish_fly/__init__.py#L390-L394

**Comment by simonw** [comment]
Used ChatGPT:

<img width="808" alt="image" src="https://user-images.githubusercontent.com/9599/211228685-a21df401-d166-4f92-bb9f-dcfc2a1ade9b.png">
